### ISSUE TITLE
Object Tracking Inference

### ISSUE THREAD

**Issue by RamkumarSakthivel** [tianweiy/CenterPoint#153]
Hi,

I have a sequence of '.pcd' files. How to run the object tracking inference using the trained model available in your model zoo. Could you please help me with the commands ?

**Comment by tianweiy** [comment]
you also need calibration files (lidar calibration, vehicle pose) for tracking, just point cloud xyz is not enough

**Comment by RamkumarSakthivel** [comment]
Hi,
Yes, I do have the calibration file with the extrinsics, device position, etc. May I know which script should I run to execute the inference please ?

**Comment by tianweiy** [comment]
Hi, there is not a single file that can work with custom data yet. The reason is that different datasets / custom data have internal variance without a standard interface. dist_test.py can work with the detection for Waymo / nuscenes and https://github.com/tianweiy/CenterPoint/blob/master/tools/simple_inference_waymo.py can work with Waymo, https://github.com/tianweiy/CenterPoint/blob/master/tools/single_infernece.py and https://github.com/tianweiy/CenterPoint/blob/master/tools/multi_sweep_inference.py can work with nuScenes for detection. For tracking, you can take a look at https://github.com/tianweiy/CenterPoint/tree/master/tools/nusc_tracking and https://github.com/tianweiy/CenterPoint/tree/master/tools/waymo_tracking

**Comment by RamkumarSakthivel** [comment]
Thank you for the information.
