### ISSUE TITLE
nusc configuration

### ISSUE THREAD

**Issue by XuyangBai** [tianweiy/CenterPoint#169]
Hi @tianweiy thanks for sharing this excellent work. May I ask for `configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py` what do you mean by `fix_bn_z`? Is the stronger data augmentation bring about 1.4% NDS compared with `centerpoint_voxel_1440_dcn` without using dcn?

**Comment by tianweiy** [comment]
fix_bn is a bug in the original repo fixed in this pull request https://github.com/tianweiy/CenterPoint/pull/109

Yes, we use a larger scaling augmentation and add a global translation here https://github.com/tianweiy/CenterPoint/blob/a3fad4201c5610aa456dfd2d513516579b88ac79/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py#L130 

and this brings some improvement

**Comment by XuyangBai** [comment]
Thanks a lot for the quick reply!
