### ISSUE TITLE
xs = xs * test_cfg.out_size_factor * test_cfg.voxel_size[0] + test_cfg.pc_range[0]

### ISSUE THREAD

**Issue by JayChan-USTC** [tianweiy/CenterPoint#273]
xs = xs * test_cfg.out_size_factor * test_cfg.voxel_size[0] + test_cfg.pc_range[0]
ys = ys * test_cfg.out_size_factor * test_cfg.voxel_size[1] + test_cfg.pc_range[1] (line 400, 401  in center_head.py)

hi,author. I have two questions , as follows:
(1)Why xs and ys are upsampled and then multiplied by test_cfg.voxel_size？Finally test_cfg.pc_range are added.

(2)What do the following parameters mean？
voxel_size=[0.2, 0.2]
pc_range=[-51.2, -51.2]
post_center_limit_range=[-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]

**Comment by tianweiy** [comment]
(1)Why xs and ys are upsampled and then multiplied by test_cfg.voxel_size？Finally test_cfg.pc_range are added.

because we do downsample in voxelization and convolutional backbone so here we essentially convert pixel location in the bird eye view map back to absolute xyz location. 

(2)What do the following parameters mean？
voxel_size=[0.2, 0.2]
pc_range=[-51.2, -51.2]
post_center_limit_range=[-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]

voxel size is essentially the voxel size (0.2meter). PC range is that our point cloud voxelization starts at -51.2 meter (x) -51.2 meter (y)

post_center_limit_range means that we filter out predictions outside of this given xyz range
