### ISSUE TITLE
about KITTI dataset

### ISSUE THREAD

**Issue by yustaub** [tianweiy/CenterPoint#54]
Hi, sir. nice work firstly. In the issue before, I notice that this codebase don't support kitti dataset, if I want to train kitti or test on kitti dataset, is there any method to do this? Very appreciate for your reply!

**Comment by tianweiy** [comment]
Hi, I tried to work on this in the past but my focus is Waymo and nuScenes at the moment. Some problems with KITTI is that it is really small (1/50 of Waymo) so that it is less diverse with really little rotated objects, pedestrians, etc.. 

I will have a large update for Waymo in the next month. I will then see if I can get time to add KITTI support. You can take a look at PV-RCNN if you want to work on KITTI at the moment https://github.com/open-mmlab/OpenPCDet

**Comment by yustaub** [comment]
Sorry for late reply. I have used OpenPCDet for kitti detection and it works well, I found that CenterPoint is excellent on nuScenes detection and tracking, so I want to use it on kitti. But is is ok, it so kind of you to reply me quickly!!!
