### ISSUE TITLE
Query on preprocessing steps

### ISSUE THREAD

**Issue by anuj-sharma-19** [tianweiy/CenterPoint#60]
Hi,

Its me again :)

I have been checking out the data pre-processing steps and have following queries:

- During training, I can see that batch sampler `DataBaseSamplerV2` removes ground truth objects with less than 5 points. And this removal is done only for the objects that are copy-pasted from other frames. But the objects in the current frame are still not removed if they have less than 5 points. Not sure if I am missing something in the data pre-processing steps?
- After copy-pasting ground truth objects point-cloud, I can see that the original points in that space are not removed `remove_points_after_sample=False`. Won't this impact training, or is it expected that the network should still be able to identify the points that belong to the objects and ignore the ones from background even though they are present in the same space very nearby?

I would highly appreciate if you could clarify these please.

Thank You.

Best Regards,
Anuj

**Comment by tianweiy** [comment]
For 1 this is expected because we are required to detect all objects with at least one lidar point. The filtering for gt augmentation is to ensure we get a high quality object to paste into other frame. Like, if it is a single point. Pasting it into a new frame may not be realistic.

For 2, your reasoning is right. I never time this parameter and I guess it doesn't matter too much as in visualization there is not much background points higher than the surface in the roads.

**Comment by anuj-sharma-19** [comment]
Thanks for the quick reply. Indeed, it makes sense to augment with only good boxes :+1:
