### ISSUE TITLE
Inference on CPU 

### ISSUE THREAD

**Issue by abhigoku10** [tianweiy/CenterPoint#85]
@tianweiy  is there any cpu version of the code available for inference ??
I am trying to build the inference part on cpu but det3d/ops/dcn and iou3dnms does not have cpu version files ? any thoughts not these

**Comment by tianweiy** [comment]
I don't have cpu implementation. You can just ignore dcn, we only use it in one model. For nms, I have a numpy implementation for a modified bev distance based nms that performs similar. I will send you link later

**Comment by tianweiy** [comment]
here https://github.com/tianweiy/CenterPoint/blob/84fde67ac35a85b0364e10e75bfdf789d578024f/det3d/core/utils/center_utils.py#L81 

For nuScenes, you can set the distance threshold according to this https://github.com/tianweiy/CenterPoint/blob/604585ac6257a6b5e3cfb531cb36adb1034c2d4c/configs/centerpoint/nusc_centerpoint_pp_02voxel_circle_nms.py#L85

**Comment by abhigoku10** [comment]
@tianweiy  thanks for quick response i have modified the following 
proposal_target_layer.py --> from ....core.utils.circle_nms_jit import circle_nms
but roi_head_template.py which calls  box_torch_ops.py has import of from det3d.ops.iou3d_nms import iou3d_nms_cuda, iou3d_nms_utils is it fine ??

**Comment by tianweiy** [comment]
yeah, all these iou3d_nms_cuda can be removed if you only use circle_nms

**Comment by abhigoku10** [comment]
@tianweiy  i added the nusc_centerpoint_pp_02voxel_circle_nms.py from the commit you provided and now i am getting this error @registery.py for return obj_cls(**args)
Exception has occurred: TypeError
__init__() got an unexpected keyword argument 'mode'

pt2: in the commit you provide is there implementation for voxel net instead of point pillar which can be used ?

**Comment by tianweiy** [comment]
Hi, there are a lot of modifications so probably you can't directly use the config from this commit. You can take a look at how we do circle_nms in this file https://github.com/tianweiy/CenterPoint/blob/604585ac6257a6b5e3cfb531cb36adb1034c2d4c/det3d/core/utils/center_utils.py#L386 and adapt the current file https://github.com/tianweiy/CenterPoint/blob/84fde67ac35a85b0364e10e75bfdf789d578024f/det3d/models/bbox_heads/center_head.py#L472

pt2: in the commit you provide is there implementation for voxel net instead of point pillar which can be used ?
this nms is agnostic to the backbone. But not sure if spconv will work on CPU

**Comment by abhigoku10** [comment]
@tianweiy  we can run an inference on cpu right since iou3dnms or dcn is not used because in ur "single inference.py" i do not see anywhere iou3dnms getting called  am i rightin understanding ??

**Comment by tianweiy** [comment]
close due to inactivity. For followers, the current codebase is probably not suited for CPU-only training. 

You also need to fix a few syntax errors if you want to run a PointPillars model on CPU for testing.
