### ISSUE TITLE
How to evaluate the trained model every n epochs?

### ISSUE THREAD

**Issue by tianqi-wang1996** [tianweiy/CenterPoint#91]
Hello, I would like to **evaluate the performance after every n epochs** which is available in mmdetection3d's CenterPoint implementation using evaluation_hook. I tried to transfer the code there into this project to make it work, but it turns out to get many errors. 

Is there a simple way to make this project be able to do that? (Such as you already implemented this, but just didn't use it)

The reason that I switch from mmdetection3d's CenterPoint implementation to this official implementation is that I found this project takes a shorter time to train, and also does a better job at test time visualization.

**Comment by tianweiy** [comment]
Yes, for nuScenes you can just modify 

https://github.com/tianweiy/CenterPoint/blob/890e538afc95ee741f4c29b4c30b37251027e31c/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_01voxel.py#L226

to 

```
workflow = [('train', x), ('val', y)]
```
x, y is the number of epochs you want. 


For Waymo, it takes more than an hour to evaluate locally so I normally just submitted it to the Waymo server, which returns results in 20-30 minutes.

**Comment by hz3014** [comment]
> Yes, for nuScenes you can just modify
> 
> https://github.com/tianweiy/CenterPoint/blob/890e538afc95ee741f4c29b4c30b37251027e31c/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_01voxel.py#L226
> 
> to
> 
> ```
> workflow = [('train', x), ('val', y)]
> ```
> 
> x, y is the number of epochs you want.
> 
> For Waymo, it takes more than an hour to evaluate locally so I normally just submitted it to the Waymo server, which returns results in 20-30 minutes.

Hi Tianweiy, I submitted a Waymo result to the server and just wondering how do i get the result? Will they email me back the result or show it on leaderboard? If it is showing result on leaderboard, not sure how to see them now since Lidar 3D detection competition expired now.

By the way, I tried python det3d/datasets/waymo/waymo_common.py --info_path data/Waymo/infos_val_01sweeps_filter_zero_gt.pkl --result_path data/Waymo/ --gt 
it gives error:
WARNING:tensorflow:From det3d/datasets/waymo/waymo_common.py:17: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

  0%|                                                                   | 0/38812 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "det3d/datasets/waymo/waymo_common.py", line 349, in <module>
    _create_gt_detection(infos, tracking=args.tracking)
  File "det3d/datasets/waymo/waymo_common.py", line 128, in _create_gt_detection
    annos = obj['objects']
KeyError: 'objects'
